import { Theme, ThemeTypeEnum } from "../theme-common";

export const defaultTheme: Theme = {
    name: "default",
    theme_type: ThemeTypeEnum.default,
    properties: {
        "--font-color-primary": "#e8eaf3",
        "--font-color-secondary": "#bfbfbf",
        "--font-link-primary": "#595c67",
        "--font-link-primary-hover": "#8f93a2",
        "--color-primary": "#141824",
        "--color-secondary": "#090b10",

        "--column-color": "#0f111a",
        "--column-header-background-color": "#0c0c10",        
        "--content-warning-background-color": "black",

        "--btn-primary-color": "#444f74",
        "--btn-primary-font-color": "white",
        "--status-primary-color": "#fff",
        "--status-secondary-color": "#4e5572",
        "--status-links-color": "#d9e1e8",
        "--boost-color": "#5098eb",
        "--update-color": "#95e470",
        "--favorite-color": "#ffc16f",
        "--bookmarked-color": "#ff5050",

        "--button-color": "#b3b3b3",
        "--button-color-hover": "white",
        "--button-border-color": "#303957",

        "--column-background": "#0f111a",

        "--card-border-color": "#2b344d",

        "--context-menu-background": "#ffffff",
        "--context-menu-background-hover": "#d7dfeb",
        "--context-menu-font-color": "#000000",
        "--context-menu-border-color": "#cbd3df",
        "--context-menu-link-profile-color": "whitesmoke",
        "--context-menu-link-profile-color-hover":"#c0c0c0",

        "--direct-message-background": "#090a0f",

        "--status-editor-title-background": "#ebebeb",
        "--status-editor-background": "#ffffff",
        "--status-editor-color": "#14151a",
        "--status-editor-footer-background": "#3e455f",
        "--status-editor-footer-link-color": "#e2e2e2",
        "--status-editor-lang-color": "#a5a5a5",
        "--status-editor-lang-background": "#ffffff00",
        "--status-editor-lang-color-hover": "#000000",
        "--status-editor-lang-background-hover": "#e6e6e6",
        "--status-editor-mention-error-color": "#ff2222",
        "--status-editor-footer-counter-color": "#e8eaf3",
        "--status-editor-footer-send-button-color": "#e8eaf3",
        "--selected-status": "#1e2734",
        "--status-content-warning-border": "#4e5572",
        "--status-content-warning-color": "whitesmoke",

        "--autosuggest-background": "#ffffff",
        "--autosuggest-entry-background": "#0f111a",
        "--autosuggest-entry-color": "#62667a",
        "--autosuggest-entry-handle-color": "#e2e2e2",
        "--autosuggest-entry-background-hover": "#2e3346",
        "--autosuggest-entry-color-hover": "#e2e2e2",
        "--autosuggest-entry-handle-color-hover": "#ffffff",

        "--scrollbar-color": "#08090d",
        "--scrollbar-color-2": "#090b10",
        "--scrollbar-color-3": "#0f111a",
        "--scrollbar-color-second-2": "#090b10",
        "--scrollbar-color-second-3": "#0f111a",

        "--poll-editor-background": "#fff",

        "--poll-editor-separator": "#e7e7e7",
        "--poll-editor-input-border": "#b9b9b9",
        "--poll-editor-input-border-focus": "#007be0",

        "--poll-color": "#e4e4e4",
        "--poll-error-color": "#ff0000",
        "--poll-refresh-color": "#6579a0",
        "--poll-color-statistics-color": "#6579a0",
        "--poll-hover-checkmark-background": "#ccc",
        "--poll-checked-checkmark-background": "#3e4b64",
        "--poll-checkmark-box-background": "#eee",
        "--poll-checkmark-round-background": "#eee",
        "--poll-checkmark-round-after-background": "#ffffff",
        "--poll-checkmark-border": "#ffffff",
        "--poll-result-percentage-color": "#ffffff",
        "--poll-result-progress-bar": "#2f4464",
        "--poll-result-progress-bar-most-votes": "#12769e",

        "--scheduler-background": "#3e455f",

        "--notification-column-selector-background": "#171c29",
        "--notification-column-selector-color": "#999fb1",
        "--notification-column-selector-color-hover": "white",

        "--settings-text-input-background": "#242836",
        "--settings-text-input-foreground": "white",
        "--settings-text-input-border": "#32384d",

        "--stream-column-icon": "whitesmoke",
        "--stream-column-icon-hover": "#acacac",
        "--stream-column-border": "#222736",
    
        "--label-bot": "#007281",
        "--label-xpost": "#9c5e00",
        "--label-thread": "#007233",
        "--label-discuss": "#5a008f",
        "--label-old": "#960000",
        "--label-remote": "#264d94",
        "--label-edited": "#5f5f5f",
    
        "--status-content-warning-closed-color": "#919bb1",
        "--status-content-warning-closed-background": "#171d2b",
    
        "--stream-edition-background": "#222736",
        "--stream-column-selector-color": "whitesmoke",

        "--stream-new-notification-1": "#96c0ff83",
        "--stream-new-notification-2": "#ffffff00",
        "--stream-new-notification-3": "#ffffff00",
        
        "--stream-remove-cw-background-hover": "#eeeeee",
        "--stream-remove-cw-color-hover": "black",
        "--stream-remove-cw-color": "white",
    
        "--stream-toot-error": "#ff7171",

        "--stream-navigation-button": "#354060",
        "--stream-navigation-button-hover": "#7a8dc7",
        "--stream-navigation-button-focus": "#f5f5f5",
        "--stream-navigation-button-focus-hover": "#f5f5f5",
        "--stream-navigation-close": "#ffffff",
    
        "--stream-toot-load-buffer-color-hover": "white",
        "--stream-toot-load-buffer-border": "black",
    
        "--stream-toot-status-not-last-child-border": "#06070b",

        "--left-bar-link": "#cbcbcb",
        "--left-bar-link-hover": "#8f93a2",
        "--left-icon-cog-color": "#cbcbcb",
        "--left-icon-cog-opacity": ".3",

        "--loading-icon-background": "#fff",

        "--profile-validated-font-color": "#4fde23",
        "--profile-validated-background": "#164109",
        "--profile-full-alias-color": "#c9c9c9",
        "--profile-full-alias-color-hover": "#ffffff",
        "--profile-floating-header-box-shadow": "#00000040",
        "--profile-floating-header-inner-background": "#00000073",
        "--profile-floating-header-name-display-name": "#ffffff",
        "--profile-moved-link": "#ffffff",
        "--profile-moved-link-hover": "#ffbe47",
        "--profile-disabled-filter": "#808080",
        "--profile-header-inner-background": "#00000073",
        "--profile-follow-button": "#ffffff",
        "--profile-follow-button-hover": "#d8d8d8",
        "--profile-followed": "#85ccff",
        "--profile-followed-hover": "#38abff",
        "--profile-header-state-data-background": "#00000099",
        "--profile-name-display-name": "#ffffff",
        "--profile-follows-border": "#0f111a",
        "--profile-follows-link": "#ffffff",
        "--profile-follows-link-background": "#1a1f2e",
        "--profile-follows-link-background-hover": "#131722",
        "--profile-extra-info-background": "#1a1f2e",
        "--profile-extra-info-floating-boxshadow": "#00000073",
        "--profile-extra-info-links": "#ffffff",
        "--profile-fields-border": "#000000",
        "--profile-lock": "#808080",
        "--profile-fields-background": "#0b0d13",

        "--floating-column-close-button": "#ffffff",
        "--floating-column-add-account-faq": "#ffcc00",
        "--floating-column-add-account-faq-hover": "#ffe88a",
        "--floating-column-add-account-faq-warning": "#ffdc52",
        "--floating-column-search-result-hashtag": "#ffffff",
        "--floating-column-settings-version": "#a1a1a1",
        "--floating-column-settings-version-hover": "#ffffff",
        "--floating-column-settings-subsection-text": "#8c98ad",
        "--floating-column-settings-subsection-title": "#ffffff",
        "--floating-column-settings-language-warning": "#ffa500",
        "--floating-column-settings-sound-select-background": "#32384d",
        "--floating-column-settings-sound-select-color": "#ffffff",
        "--floating-column-settings-sound-select-border": "#32384d",
        "--floating-column-settings-sound-play-background": "#1f2330",
        "--floating-column-settings-sound-play-color": "#ffffff",
        "--floating-column-settings-sound-play-background-hover": "#32384d",
        "--floating-column-settings-toggle-lock": "#ffffff",
        "--floating-column-settings-toggle-lock-background": "#1f2330",
        "--floating-column-settings-toggle-lock-background-hover": "#32384d",
        "--floating-column-manage-account-header-border": "#222736",
        "--floating-column-manage-account-header-selected": "#f5f5f5",
        "--floating-column-manage-account-header-selected-hover": "#f5f5f5",
        "--floating-column-manage-account-header-notification": "#fa9829",
        "--floating-column-manage-account-header-notification-hover": "#ffb96a",
        "--floating-column-manage-account-dm-icon": "#5098eb",
        "--floating-column-manage-account-dm-stream-border": "#232733",
        "--floating-column-manage-account-myaccount-blue": "#ffffff",
        "--floating-column-manage-account-myaccount-red": "#ffffff",
        "--floating-column-manage-account-myaccount-red-background": "#410303",
        "--floating-column-manage-account-myaccount-red-background-hover": "#4a0303",
        "--floating-column-manage-account-myaccount-list-button-hover": "#ffffff",
        "--floating-column-manage-account-myaccount-list-new": "#ffffff",
        "--floating-column-manage-account-myaccount-advanced-text": "#8c98ad",
        "--floating-column-manage-account-notification-stream-error": "#ff7171",
        "--floating-column-manage-account-notification-border": "#06070b",
        "--floating-column-manage-account-notification-follow-account-display-name": "#f5f5f5",
        "--floating-column-manage-account-notification-follow-request-link": "#b6b6b6",
        "--floating-column-manage-account-notification-follow-request-link-validate": "#adff2f",
        "--floating-column-manage-account-notification-follow-request-link-refuse": "#ff4500",

        "--stream-selection-representation-background": "#595c67",
        "--stream-selection-representation-hover-background": "#8f93a2",
        "--stream-selection-representation-selected-background": "#a8a8a8",
        "--stream-selection-representation-selected-hover-background": "#ffffff",

        "--tutorial-bg-primary": "#1d2335",
        "--tutorial-bg-secondary": "#0075ac",
        "--tutorial-bg-tertiary": "#00547a",
        "--tutorial-bg-quaternary": "#004a6d",
        "--tutorial-text-primary": "#ffffff",
        "--tutorial-text-secondary": "#4e5672",
        "--tutorial-text-muted": "#dadada",
        "--tutorial-border": "#00547a",
        "--tutorial-button-hover": "#e6e6e6",
        "--tutorial-close": "#808080",

        "--notification-success-bg": "#22b90e",
        "--notification-success-fg": "#000000",
        "--notification-error-bg": "#be0a0a",
        "--notification-error-fg": "#f5f5f5",
        "--notification-text-muted": "rgba(255, 255, 255, 0.6)",

        "--draggable-accent": "#47e927",
        "--language-warning": "#ffa500",
        "--language-warning-link": "#f0d124",
        "--language-warning-link-hover": "#d18800",
        "--context-menu-icon": "#1f1f1f",

        "--card-provider": "#f5f5f5",
        "--card-image-overlay": "rgba(0, 0, 0, 0.85)",
        "--card-error-bg": "#000000",
        "--attachment-outline-warning": "#ffa500",
        "--attachment-bg": "#000000",
        "--attachment-icon": "#d3d3d3",
        "--attachment-icon-alt": "#ffffff",
        "--attachment-gradient-start": "rgba(0, 0, 0, 0.5)",
        "--attachment-gradient-end": "rgba(0, 0, 0, 0)",

        "--link-primary": "#a9b5d8",
        "--link-secondary": "#c0c8e0",
        "--link-hover": "#ffffff",
        "--mention": "#a0d1ff",
        "--code-bg": "#000000",
        "--code-block-bg": "#384958",

        "--hashtag-border": "#000000",
        "--hashtag-text": "#ffffff",

        "--media-viewer-icon": "#f5f5f5",
        "--media-viewer-overlay": "rgba(0, 0, 0, 0.8)",

        "--account-icon-warning-border": "#ffa500",
        "--account-icon-warning": "#ffa500",
        "--account-icon-overlay": "rgba(0, 0, 0, 0.55)",

        "--list-editor-text-primary": "#ffffff",
        "--list-editor-text-secondary": "#ffffff",
        "--list-editor-text-muted": "#a0a0a0",
        "--list-editor-border": "#000000",
        "--list-account-text": "#ffffff",
        "--list-account-text-dimmed": "#cccccc",
        "--list-account-text-secondary": "#ffffff",

        "--scheduled-status-muted": "#808080",
        "--scheduled-status-delete-bg-1": "#5f0505",
        "--scheduled-status-delete-bg-2": "#a30404",

        "--scheduler-text": "#f5f5f5",
        "--scheduler-text-secondary": "#cccccc",

        "--poll-editor-text-primary": "#313131",
        "--poll-editor-text-secondary": "#7a7a7a",
        "--poll-entry-text-muted": "#8b8b8b",
        "--poll-entry-text-primary": "#000000",
        "--poll-entry-border": "#646464",

        "--stream-overlay-border": "#f5f5f5",
        "--stream-overlay-text-muted": "#808080",

        "--app-overlay-bg": "rgba(0, 0, 0, 0.8)",
        "--app-drag-border": "#000000",
        "--app-notification-text": "#000418",
        "--app-notification-shadow": "#000000",
        "--app-button-primary": "#ffffff",
        "--app-button-primary-bg": "#3e455f",
        "--app-button-secondary-bg": "#1d202c",
        "--app-media-overlay": "rgba(0, 0, 0, 0.9)",

        "--streams-shadow": "rgba(0, 0, 0, 0.5)",

        "--button-danger-bg": "#410303",
        "--button-danger-bg-hover": "#721515",
        "--button-danger-color": "#ffffff",

        "--context-menu-shadow": "rgba(0, 0, 0, 0.5)",

        "--media-overlay-bg": "rgba(0, 0, 0, 0.5)",
        "--media-overlay-bg-hover": "rgba(0, 0, 0, 0.7)",
        "--media-icon": "#ffffff",

        "--attachment-icon-overlay": "#ffffff",
        "--attachment-icon-shadow": "#4e4e4e",
        "--attachment-icon-shadow-hover": "#4e4e4e"
    }
};