import { Theme, ThemeTypeEnum } from "../theme-common";

export const tokyoNightTheme: Theme = {
    name: "tokyo-night",
    theme_type: ThemeTypeEnum.tokyoNight,
    properties: {
        "--font-color-primary": "#a9b1d6",
        "--font-color-secondary": "#565f89",
        "--font-link-primary": "#7aa2f7",
        "--font-link-primary-hover": "#bb9af7",
        "--color-primary": "#24283b",
        "--color-secondary": "#1a1b26",

        "--column-color": "#1a1b26",
        "--column-header-background-color": "#16161e",        
        "--content-warning-background-color": "#0f0f14",

        "--btn-primary-color": "#7aa2f7",
        "--btn-primary-font-color": "#1a1b26",
        "--status-primary-color": "#c0caf5",
        "--status-secondary-color": "#565f89",
        "--status-links-color": "#7aa2f7",
        "--boost-color": "#9ece6a",
        "--update-color": "#7dcfff",
        "--favorite-color": "#f7768e",
        "--bookmarked-color": "#ff9e64",

        "--button-color": "#a9b1d6",
        "--button-color-hover": "#c0caf5",
        "--button-border-color": "#414868",

        "--column-background": "#1a1b26",

        "--card-border-color": "#414868",

        "--context-menu-background": "#24283b",
        "--context-menu-background-hover": "#2e3c64",
        "--context-menu-font-color": "#a9b1d6",
        "--context-menu-border-color": "#414868",
        "--context-menu-link-profile-color": "whitesmoke",
        "--context-menu-link-profile-color-hover":"#c0c0c0",

        "--direct-message-background": "#16161e",

        "--status-editor-title-background": "#1a1b26",
        "--status-editor-background": "#24283b",
        "--status-editor-color": "#a9b1d6",
        "--status-editor-footer-background": "#414868",
        "--status-editor-footer-link-color": "#7aa2f7",
        "--status-editor-lang-color": "#565f89",
        "--status-editor-lang-background": "#1a1b26",
        "--status-editor-lang-color-hover": "#a9b1d6",
        "--status-editor-lang-background-hover": "#2e3c64",
        "--status-editor-mention-error-color": "#f7768e",
        "--status-editor-footer-counter-color": "#a9b1d6",
        "--status-editor-footer-send-button-color": "#1a1b26",
        "--selected-status": "#2e3c64",
        "--status-content-warning-border": "#565f89",
        "--status-content-warning-color": "whitesmoke",

        "--autosuggest-background": "#24283b",
        "--autosuggest-entry-background": "#1a1b26",
        "--autosuggest-entry-color": "#a9b1d6",
        "--autosuggest-entry-handle-color": "#7aa2f7",
        "--autosuggest-entry-background-hover": "#2e3c64",
        "--autosuggest-entry-color-hover": "#c0caf5",
        "--autosuggest-entry-handle-color-hover": "#bb9af7",

        "--scrollbar-color": "#0f0f14",
        "--scrollbar-color-2": "#16161e",
        "--scrollbar-color-3": "#1a1b26",
        "--scrollbar-color-second-2": "#16161e",
        "--scrollbar-color-second-3": "#1a1b26",

        "--poll-editor-background": "#24283b",

        "--poll-editor-separator": "#414868",
        "--poll-editor-input-border": "#565f89",
        "--poll-editor-input-border-focus": "#7aa2f7",

        "--poll-color": "#a9b1d6",
        "--poll-error-color": "#f7768e",
        "--poll-refresh-color": "#7aa2f7",
        "--poll-color-statistics-color": "#7aa2f7",
        "--poll-hover-checkmark-background": "#414868",
        "--poll-checked-checkmark-background": "#7aa2f7",
        "--poll-checkmark-box-background": "#2e3c64",
        "--poll-checkmark-round-background": "#2e3c64",
        "--poll-checkmark-round-after-background": "#a9b1d6",
        "--poll-checkmark-border": "#414868",
        "--poll-result-percentage-color": "#a9b1d6",
        "--poll-result-progress-bar": "#414868",
        "--poll-result-progress-bar-most-votes": "#7aa2f7",

        "--scheduler-background": "#414868",

        "--notification-column-selector-background": "#1f2335",
        "--notification-column-selector-color": "#565f89",
        "--notification-column-selector-color-hover": "#a9b1d6",

        "--settings-text-input-background": "#1a1b26",
        "--settings-text-input-foreground": "#a9b1d6",
        "--settings-text-input-border": "#414868",

        "--stream-column-icon": "whitesmoke",
        "--stream-column-icon-hover": "#bb9af7",
        "--stream-column-border": "#24283b",
    
        "--label-bot": "#7dcfff",
        "--label-xpost": "#e0af68",
        "--label-thread": "#9ece6a",
        "--label-discuss": "#bb9af7",
        "--label-old": "#f7768e",
        "--label-remote": "#7aa2f7",
        "--label-edited": "#565f89",
    
        "--status-content-warning-closed-color": "#565f89",
        "--status-content-warning-closed-background": "#1a1b26",
    
        "--stream-edition-background": "#24283b",
        "--stream-column-selector-color": "whitesmoke",

        "--stream-new-notification-1": "#7aa2f780",
        "--stream-new-notification-2": "#ffffff00",
        "--stream-new-notification-3": "#ffffff00",
        
        "--stream-remove-cw-background-hover": "#2e3c64",
        "--stream-remove-cw-color-hover": "#a9b1d6",
        "--stream-remove-cw-color": "whitesmoke",
    
        "--stream-toot-error": "#f7768e",

        "--stream-navigation-button": "#414868",
        "--stream-navigation-button-hover": "#7aa2f7",
        "--stream-navigation-button-focus": "#a9b1d6",
        "--stream-navigation-button-focus-hover": "#c0caf5",
        "--stream-navigation-close": "#f7768e",
    
        "--stream-toot-load-buffer-color-hover": "#c0caf5",
        "--stream-toot-load-buffer-border": "#1a1b26",
    
        "--stream-toot-status-not-last-child-border": "#0f0f14",

        "--left-bar-link": "#a9b1d6",
        "--left-bar-link-hover": "#7aa2f7",
        "--left-icon-cog-color": "#a9b1d6",
        "--left-icon-cog-opacity": ".3",
        "--left-icon-scheduled-color": "#7dcfff",

        "--loading-icon-background": "#7aa2f7",

        "--profile-validated-font-color": "#9ece6a",
        "--profile-validated-background": "#1a1b26",
        "--profile-full-alias-color": "#565f89",
        "--profile-full-alias-color-hover": "#a9b1d6",
        "--profile-floating-header-box-shadow": "#00000040",
        "--profile-floating-header-inner-background": "#16161e73",
        "--profile-floating-header-name-display-name": "#c0caf5",
        "--profile-moved-link": "#c0caf5",
        "--profile-moved-link-hover": "#e0af68",
        "--profile-disabled-filter": "#565f89",
        "--profile-header-inner-background": "#16161e73",
        "--profile-follow-button": "#c0caf5",
        "--profile-follow-button-hover": "#7aa2f7",
        "--profile-followed": "#bb9af7",
        "--profile-followed-hover": "#7dcfff",
        "--profile-header-state-data-background": "#00000099",
        "--profile-name-display-name": "#c0caf5",
        "--profile-follows-border": "#1a1b26",
        "--profile-follows-link": "#c0caf5",
        "--profile-follows-link-background": "#24283b",
        "--profile-follows-link-background-hover": "#1a1b26",
        "--profile-extra-info-background": "#24283b",
        "--profile-extra-info-floating-boxshadow": "#00000073",
        "--profile-extra-info-links": "#c0caf5",
        "--profile-fields-border": "#414868",
        "--profile-lock": "#565f89",
        "--profile-fields-background": "#16161e",

        "--floating-column-close-button": "#f7768e",
        "--floating-column-add-account-faq": "#e0af68",
        "--floating-column-add-account-faq-hover": "#ff9e64",
        "--floating-column-add-account-faq-warning": "#f7768e",
        "--floating-column-search-result-hashtag": "#7aa2f7",
        "--floating-column-settings-version": "#565f89",
        "--floating-column-settings-version-hover": "#a9b1d6",
        "--floating-column-settings-subsection-text": "#565f89",
        "--floating-column-settings-subsection-title": "#c0caf5",
        "--floating-column-settings-language-warning": "#e0af68",
        "--floating-column-settings-sound-select-background": "#1a1b26",
        "--floating-column-settings-sound-select-color": "#a9b1d6",
        "--floating-column-settings-sound-select-border": "#414868",
        "--floating-column-settings-sound-play-background": "#24283b",
        "--floating-column-settings-sound-play-color": "#a9b1d6",
        "--floating-column-settings-sound-play-background-hover": "#2e3c64",
        "--floating-column-settings-toggle-lock": "#a9b1d6",
        "--floating-column-settings-toggle-lock-background": "#1a1b26",
        "--floating-column-settings-toggle-lock-background-hover": "#2e3c64",
        "--floating-column-manage-account-header-border": "#24283b",
        "--floating-column-manage-account-header-selected": "#c0caf5",
        "--floating-column-manage-account-header-selected-hover": "#7aa2f7",
        "--floating-column-manage-account-header-notification": "#e0af68",
        "--floating-column-manage-account-header-notification-hover": "#ff9e64",
        "--floating-column-manage-account-dm-icon": "#7aa2f7",
        "--floating-column-manage-account-dm-stream-border": "#24283b",
        "--floating-column-manage-account-myaccount-blue": "#7aa2f7",
        "--floating-column-manage-account-myaccount-red": "#f7768e",
        "--floating-column-manage-account-myaccount-red-background": "#3b1923",
        "--floating-column-manage-account-myaccount-red-background-hover": "#4a1f2b",
        "--floating-column-manage-account-myaccount-list-button-hover": "#7aa2f7",
        "--floating-column-manage-account-myaccount-list-new": "#c0caf5",
        "--floating-column-manage-account-myaccount-advanced-text": "#565f89",
        "--floating-column-manage-account-notification-stream-error": "#f7768e",
        "--floating-column-manage-account-notification-border": "#0f0f14",
        "--floating-column-manage-account-notification-follow-account-display-name": "#c0caf5",
        "--floating-column-manage-account-notification-follow-request-link": "#565f89",
        "--floating-column-manage-account-notification-follow-request-link-validate": "#9ece6a",
        "--floating-column-manage-account-notification-follow-request-link-refuse": "#f7768e",

        "--stream-selection-representation-background": "#565f89",
        "--stream-selection-representation-hover-background": "#7aa2f7",
        "--stream-selection-representation-selected-background": "#a9b1d6",
        "--stream-selection-representation-selected-hover-background": "#c0caf5",

        "--tutorial-bg-primary": "#24283b",
        "--tutorial-bg-secondary": "#7aa2f7",
        "--tutorial-bg-tertiary": "#565f89",
        "--tutorial-bg-quaternary": "#414868",
        "--tutorial-text-primary": "#c0caf5",
        "--tutorial-text-secondary": "#7aa2f7",
        "--tutorial-text-muted": "#565f89",
        "--tutorial-border": "#7aa2f7",
        "--tutorial-button-hover": "#2e3c64",
        "--tutorial-close": "#f7768e",
        "--tutorial-arrow-1": "url('assets/img/arrow_1.png')",
        "--tutorial-arrow-2": "url('assets/img/arrow_2.png')",

        "--notification-success-bg": "#9ece6a",
        "--notification-success-fg": "#1a1b26",
        "--notification-error-bg": "#f7768e",
        "--notification-error-fg": "#1a1b26",
        "--notification-text-muted": "rgba(169, 177, 214, 0.6)",

        "--draggable-accent": "#7dcfff",
        "--language-warning": "#e0af68",
        "--language-warning-link": "#ff9e64",
        "--language-warning-link-hover": "#f7768e",
        "--context-menu-icon": "#7aa2f7",

        "--card-provider": "#c0caf5",
        "--card-image-overlay": "rgba(26, 27, 38, 0.85)",
        "--card-error-bg": "#1a1b26",
        "--attachment-outline-warning": "#e0af68",
        "--attachment-bg": "#1a1b26",
        "--attachment-icon": "#a9b1d6",
        "--attachment-icon-alt": "#c0caf5",
        "--attachment-gradient-start": "rgba(26, 27, 38, 0.5)",
        "--attachment-gradient-end": "rgba(26, 27, 38, 0)",

        "--post-expander-link": "#7aa2f7",
        "--post-expander-link-hover": "#bb9af7",
        "--post-expander-background": "#1a1b26",
        "--post-expander-background-25-opacity": "#1a1b263a",
        "--post-expander-background-50-opacity": "#1a1b2683",
        
        "--code-post-color": "#7dcfff",
        
        "--post-scrollbar-background": "#1a1b26",
        "--post-scrollbar-thumb-background": "#414868",

        "--hashtag-border": "#414868",
        "--hashtag-text": "#7aa2f7",

        "--media-viewer-icon": "#c0caf5",
        "--media-viewer-overlay": "rgba(26, 27, 38, 0.9)",

        "--account-icon-warning-border": "#e0af68",
        "--account-icon-warning": "#e0af68",
        "--account-icon-overlay": "rgba(26, 27, 38, 0.55)",

        "--list-editor-text-search": "#a9b1d6",
        "--list-editor-close-search": "#a9b1d6",
        "--list-editor-close-search-hover": "#f7768e",
        "--list-editor-border": "#414868",
        "--list-account-text": "#c0caf5",
        "--list-account-text-hover": "#a9b1d6",
        "--list-account-text-secondary": "#565f89",

        "--scheduled-status-content-spoiler": "#565f89",
        "--scheduled-status-delete-bg": "#3b1923",
        "--scheduled-status-delete-bg-hover": "#4a1f2b",

        "--scheduler-text": "#a9b1d6",
        "--scheduler-text-hover": "#c0caf5",

        "--poll-editor-add-choice-color": "#565f89",
        "--poll-editor-add-choice-color-hover": "#7aa2f7",
        "--poll-entry-remove-link": "#f7768e",
        "--poll-entry-text-primary": "#a9b1d6",
        "--poll-entry-border": "#414868",

        "--stream-overlay-border": "#7aa2f7",
        "--stream-overlay-text-muted": "#565f89",

        "--app-drag-and-drop-bg": "rgba(26, 27, 38, 0.8)",
        "--app-drag-and-drop-border": "#7aa2f7",
        "--app-auto-update-color": "#1a1b26",
        "--app-auto-update-shadow": "#000000",
        "--reload-button-color": "#1a1b26",
        "--reload-button-color-bg": "#7aa2f7",
        "--reload-button-bg-hover": "#bb9af7",
        "--app-media-overlay": "rgba(26, 27, 38, 0.9)",

        "--streams-shadow": "rgba(0, 0, 0, 0.5)",

        "--button-danger-bg": "#3b1923",
        "--button-danger-bg-hover": "#4a1f2b",
        "--button-contrast-color": "#1a1b26",

        "--context-menu-shadow": "rgba(0, 0, 0, 0.5)",

        "--media-overlay-bg": "rgba(26, 27, 38, 0.5)",
        "--media-overlay-bg-hover": "rgba(26, 27, 38, 0.7)",
        "--media-button-color": "#c0caf5",

        "--attachment-icon-overlay": "#c0caf5",
        "--attachment-icon-shadow": "#1a1b26",
        "--attachment-icon-shadow-hover": "#24283b"
    }
};
