name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Pre-publication clean-up
      run: rm -rf ./dist/assets/emoji
    
    - name: Web Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with: 
        server: ${{ secrets.ftpserver }}
        username: ${{ secrets.ftpusername }}
        password: ${{ secrets.ftppassword }}
        local_path: './dist/*'
        remote_path: './'
        port: 22
        sftp_only: true
